name: CI
on: 
  push:
    branches:
      - main
      - dev
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run typescript type check
      run: npm run typecheck
    - name: Run ESLint
      run: npm run lint
